# Generated by Django 5.2.4 on 2025-07-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
    ]
